// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fzcoljqdtmkgrswwxkyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6Y29sanFkdG1rZ3Jzd3d4a3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1MzU4NzIsImV4cCI6MjA5NzExMTg3Mn0.bMO4poe2Zs_c_zTor5gFf2BFvRIWSKF6j9OtCdFnOdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);